version: "3.7"

services:
  pihole:
    container_name: PiHole
    image: pihole/pihole:latest
    restart: always
    environment:
      TZ: "Europe/Sofia"
      WEBPASSWORD: p1_h0l3
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /home/$USER/pihole/etc-pihole/:/etc/pihole/
      - /home/$USER/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
