version: "3.7"

services:
  octoprint:
    container_name: Octoprint
    image: octoprint/octoprint:latest
    restart: always
    environment:
      ENABLE_MJPG_STREAMER: "true"
      # https://icecat.biz/en/p/logitech/960-000244/webcams-quickcam+s5500-1840109.html
      # Logitech QuickCam S5500
      # 1280 x 960 pixels, 30 fps
      MJPG_STREAMER_INPUT: "-y -n -r 1280x960 -f 30"
    ports:
      - 8080:80
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
      - /home/$USER/octoprint_data/:/octoprint
