version: '3.7'

services:
  octoprint:
    image: octoprint/octoprint:latest
    container_name: Octoprint
    environment:
      - ENABLE_MJPG_STREAMER=true
      - CAMERA_DEV=/dev/video0
      - MJPG_STREAMER_INPUT="-y -n -r 1280x960 -f 30"
    restart: unless-stopped
    ports:
      - 80:80
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
      - ./octoprint_data_volume/:/octoprint
