version: "3.7"

services:
  octoprint:
    image: octoprint/octoprint:latest
    container_name: Octoprint
    restart: always
    environment:
      ENABLE_MJPG_STREAMER: "true"
      MJPG_STREAMER_INPUT: "-y -n -r ${CAMERA_RESOLUTION} -f ${CAMERA_FPS}"
    ports:
      - 80:80
    devices:
      - ${USB_PORT}:${USB_PORT}
      - ${CAMERA_DEV}:${CAMERA_DEV}
    volumes:
      - ${OCTOPRINT_DATA}:/octoprint
